In [25]:
import pandas as pd
import numpy as np

In [26]:
df=pd.DataFrame({'text': ['people watch tv', 'tv watch tv', 'people write comment', 'tv write comment'], 'output':[1,1,0,0]})

In [27]:
df

text  output
0       people watch tv       1
1           tv watch tv       1
2  people write comment       0
3      tv write comment       0

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [29]:
# bag of words:
bow=cv.fit_transform(df['text'])


In [30]:
#vocab:
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'tv': 2, 'write': 4, 'comment': 0}


In [31]:
# alphabatical order me frequency-
# comment, people, tv, watch, write
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 1 1 0]]
[[0 0 2 1 0]]
[[1 1 0 0 1]]
[[1 0 1 0 1]]


In [32]:
cv.transform(['tv watch and write comment of tv and radio']).toarray()
# words that were not present in trianing are ignored
#stopwords are also ignored

array([[1, 0, 2, 1, 1]])

In [33]:
# read cv doc

In [34]:
# # hyperperameters
# binary- 0/1 for presence/absence of the word instead of showing freq
# max_feature- int, top freq n cols only


# N Grams

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,2)) #1 and 2 k combination of each Ds
# cv=CountVectorizer(ngram_range=(2,4)) #2 and 4 k combination of each Ds, but 4 words to kisi bhi D me nhi he so, will through an error

In [36]:
bow=cv.fit_transform(df['text'])

In [37]:
cv.vocabulary_

{'people': 1,
 'watch': 7,
 'tv': 4,
 'people watch': 2,
 'watch tv': 8,
 'tv watch': 5,
 'write': 9,
 'comment': 0,
 'people write': 3,
 'write comment': 10,
 'tv write': 6}

In [38]:
print(len(cv.vocabulary_))

11


In [39]:
# bigrams-6
#unigrams- 5*1
# tot= 11

In [40]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 0 1 0 0 1 1 0 0]]
[[0 0 0 0 2 1 0 1 1 0 0]]
[[1 1 0 1 0 0 0 0 0 1 1]]


# TF - IDF

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [42]:
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray() # since it return sparse matrix, so toarray me cnvrtd

array([[0.        , 0.61366674, 0.49681612, 0.61366674, 0.        ],
       [0.        , 0.        , 0.8508161 , 0.52546357, 0.        ],
       [0.57735027, 0.57735027, 0.        , 0.        , 0.57735027],
       [0.61366674, 0.        , 0.49681612, 0.        , 0.61366674]])

In [43]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())


[1.51082562 1.51082562 1.22314355 1.51082562 1.51082562]
['comment' 'people' 'tv' 'watch' 'write']
